# Generated by Django 4.1b1 on 2022-07-01 03:24

# 教學說明：
# 這是第一版 migration，會建立 Topic 資料表。
# migration 檔案通常由 makemigrations 自動產生，
# 不建議手動修改欄位內容，除非你清楚資料庫遷移後果。

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
