# Generated by Django 6.0.3 on 2026-04-01 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenserecord',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
