# Generated by Django 6.0.3 on 2026-05-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_mgt', '0003_expenserecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserecord',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
